# ----------------------------------------------------------------------
# Secrets — auto-generated by Terraform, stored in AWS Secrets Manager
# ----------------------------------------------------------------------
#
# Cloud-init fetches these at boot via the EC2 instance role's
# secretsmanager:GetSecretValue grant (scoped to these ARNs in iam.tf).
# Values are NOT in user_data — only the ARNs are — so the secrets
# never leave Secrets Manager unencrypted.
#
# Only two secrets remain: the encryption key (Secrets Manager stays
# its authority on AWS) and the one-time claim token that unlocks the
# in-product setup wizard. Everything else the installer used to
# deliver (JWT secret, seed admin password, Slack tokens) is either
# self-generated by the platform on first boot or configured through
# the wizard / instance settings.
#
# recovery_window_in_days = 7 puts secrets into soft-delete for a week
# after `terraform destroy` before permanent removal — leaves a recovery
# window in case the destroy was a mistake.

# Credential-proxy encryption key. 32 bytes hex (AES-256).
# Compromise = every stored credential's wrapping key is exposed.
resource "random_id" "encryption_key" {
  byte_length = 32
}

resource "aws_secretsmanager_secret" "encryption_key" {
  name        = "${local.name}/encryption-key"
  description = "AES-256 wrapping key for credential-proxy. Treat as the most sensitive secret in the system — its compromise exposes every stored vendor credential."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "encryption_key" {
  secret_id     = aws_secretsmanager_secret.encryption_key.id
  secret_string = random_id.encryption_key.hex
}

# One-time claim token for the in-product setup wizard. 32 bytes hex.
# Delivered to the instance via .env and printed to the operator via
# the `claim_token` output; the platform stores only its hash and the
# token is inert once setup completes. Rotate a lost token on-host with
# `exo-reissue-claim-token` (no instance replacement needed).
resource "random_id" "claim_token" {
  byte_length = 32
}

resource "aws_secretsmanager_secret" "claim_token" {
  name        = "${local.name}/claim-token"
  description = "One-time claim token for the setup wizard. Inert after first-boot setup completes."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "claim_token" {
  secret_id     = aws_secretsmanager_secret.claim_token.id
  secret_string = random_id.claim_token.hex
}
