# ----------------------------------------------------------------------
# Secrets — auto-generated by Terraform, stored in AWS Secrets Manager
# ----------------------------------------------------------------------
#
# Cloud-init fetches these at boot via the EC2 instance role's
# secretsmanager:GetSecretValue grant (scoped to these ARNs in iam.tf).
# Values are NOT in user_data — only the ARNs are — so the secrets
# never leave Secrets Manager unencrypted.
#
# random_id (jwt + encryption_key) is used instead of random_password
# for keys that should be hex-encoded byte strings; random_password is
# used for the seed admin password where character classes matter.
#
# recovery_window_in_days = 7 puts secrets into soft-delete for a week
# after `terraform destroy` before permanent removal — leaves a recovery
# window in case the destroy was a mistake.

# JWT signing secret for the gateway. 256 bits hex.
resource "random_id" "jwt_secret" {
  byte_length = 32
}

resource "aws_secretsmanager_secret" "jwt" {
  name        = "${local.name}/jwt-secret"
  description = "Gateway JWT signing secret for the Ghost Agent Platform deployment."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id     = aws_secretsmanager_secret.jwt.id
  secret_string = random_id.jwt_secret.hex
}

# Credential-proxy encryption key. 32 bytes hex (AES-256).
# Compromise = every stored credential's wrapping key is exposed.
resource "random_id" "encryption_key" {
  byte_length = 32
}

resource "aws_secretsmanager_secret" "encryption_key" {
  name        = "${local.name}/encryption-key"
  description = "AES-256 wrapping key for credential-proxy. Treat as the most sensitive secret in the system — its compromise exposes every stored vendor credential."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "encryption_key" {
  secret_id     = aws_secretsmanager_secret.encryption_key.id
  secret_string = random_id.encryption_key.hex
}

# Initial admin password. Limited to terminal-safe specials to avoid
# shell-quoting surprises during retrieval. Should be rotated in-app
# after first login.
resource "random_password" "seed_admin" {
  length           = 24
  special          = true
  override_special = "!@#%^*-_=+"
}

resource "aws_secretsmanager_secret" "seed_admin_password" {
  name        = "${local.name}/seed-admin-password"
  description = "Initial admin password for ${var.seed_admin_email}. Should be rotated in-app after first login."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "seed_admin_password" {
  secret_id     = aws_secretsmanager_secret.seed_admin_password.id
  secret_string = random_password.seed_admin.result
}

# Slack channel-connector credentials (optional). The value is set
# out-of-band via the AWS console / CLI when the integration is enabled.
# Terraform creates the secret unconditionally so the IAM role's grant
# works regardless; the initial value is an empty JSON object, and
# subsequent edits are ignored so out-of-band updates don't drift.
resource "aws_secretsmanager_secret" "slack" {
  name        = "${local.name}/slack"
  description = "Optional Slack channel-connector credentials. JSON-shaped: {\"app_token\":\"xapp-...\",\"bot_token\":\"xoxb-...\",\"signing_secret\":\"...\"}. Leave the empty default to disable Slack integration."
  tags        = local.common_tags

  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "slack" {
  secret_id     = aws_secretsmanager_secret.slack.id
  secret_string = jsonencode({})

  lifecycle {
    ignore_changes = [secret_string] # operator-managed value
  }
}
